replicaCount: 2
image:
  repository: ghcr.io/rsk0-app/inventory-service
  tag: 35e87f5b1a5f7a47f85a3be6c118962b08449bec
  pullPolicy: Always
service:
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  ENVIRONMENT: production
  MEM_FOOTPRINT_MB: "150"
database:
  url: postgres://stand:standpass@postgres.rsk0-apps.svc.cluster.local:5432/stand
failure:
  mode: ""
  errorRate: "0"
  latencyMs: "0"
