replicaCount: 1
image:
  repository: ghcr.io/rsk0-app/inventory-service
  tag: 73e71599be700c1eb9eb17639f026085c4a25099
  pullPolicy: Always
service:
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  ENVIRONMENT: production
  MEM_FOOTPRINT_MB: "150"
database:
  url: postgres://stand:standpass@postgres.rsk0-apps.svc.cluster.local:5432/stand
failure:
  mode: ""
  errorRate: "0"
  latencyMs: "0"
