apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-service
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
